// components/Header.tsx
import Link from "next/link";

export default function Header() {
  return (
    <header className="w-full flex items-center justify-between">
      <div className="flex flex-col">
        <span className="font-semibold text-lg text-zinc-200">
          Vittor de Aguiar
        </span>
        <span className="font-medium text-base text-zinc-400">
          Full Stack Developer
        </span>
      </div>

      <div>
        <Link href={"/about"}>
          <span className="text-base text-zinc-400 cursor-pointer hover:text-zinc-600">
            /about
          </span>
        </Link>
      </div>
    </header>
  );
}

// src/components/Header.vue
<script setup lang="ts">
  const menuItems = [{ text: 'Home', link: '/' }]
  // const menuItems = ['Home', 'Projects', 'About']
</script>

<template>
  <header class="h-32 md:px-96 px-8 flex items-center justify-between">
    <section class="flex flex-col">
      <h1>Vittor de Aguiar</h1>
      <p>Full Stack Developer</p>
    </section>
    <section class="flex items-center space-x-4">
      <a
        v-for="item in menuItems"
        :href="item.link"
        class="cursor-pointer transition-transform transform hover:scale-105 underline"
      >
        {{ item.text }}
      </a>
    </section>
  </header>
</template>
